Projet2/Models/Boutique/Assortiment.cs
using System;
using System.Collections.Generic;
using Projet2.Models.Compte;

namespace Projet2.Models.Boutique
{
    public class Assortiment
    {
        public int Id { get; set; }

        public List<Article> Articles { get; set; }

    }
}

Projet2/Models/Boutique/Avis.cs
using Projet2.Models.Compte;
using Projet2.Models.PanierSaisonniers;
using System;
namespace Projet2.Models.Boutique
{
    public class Avis
    {
        public int Id { get; set; }
        public String Text { get; set; }
        public int Note { get; set; }

        public int? ArticleId { get; set; }
        public Article Article { get; set; }

        public int? PanierSaisonnierId { get; set; }
        public PanierSaisonnier PanierSaisonnier { get; set; }


        public AdA AdA { get; set; }
        public int? AdAId { get; set; }

        public Entreprise Entreprise { get; set; }
        public int? EntrepriseId { get; set; }

    }
}

Projet2/Models/Boutique/Boutique.cs
using System;
using System.Collections.Generic;

namespace Projet2.Models.Boutique
{
    public class Boutiques
    {
        public int Id { get; set; }
        public int NombreArticle { get; set; }

        public virtual List<Article> Articles { get; set; }

    }
}

Projet2/Models/Boutique/PaimentService.cs
using System;
namespace Projet2.Models.Boutique
{
    public class PaimentService
    {
        private BddContext _bddContext;
        public PaimentService()
        {
            _bddContext = new BddContext();
        }

        public void CreerCommande()
        {

        }
    }
}

Projet2/Controllers/CompteAdPController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Projet2.Helpers;
using Projet2.Models.Compte;
using Projet2.ViewModels;
using System.Collections.Generic;
using System.IO;
using System.Security.Claims;

namespace Projet2.Controllers
{
    [Authorize]
    public class CompteAdPController : Controller
    {
        //ajouter RIB
        //adresse avec base de données ? 
       
        CompteServices cs = new CompteServices();
        HomeViewModel hvm = new HomeViewModel();

        private readonly IWebHostEnvironment _webHostEnvironment;

        public CompteAdPController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index(AdP adp)
        {
            hvm.Personne = cs.ObtenirPersonne(adp.PersonneId);

            if (hvm.Personne == null)
            {
                UtilisateurViewModel viewModel = new UtilisateurViewModel() { Authentifie = SessionHelper.GetObjectFromJson<bool>(HttpContext.Session, "authentification") };
                viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);
                hvm.AdP = cs.ObtenirAdPParIdentifiant(viewModel.Identifiant.Id);
                if (hvm.AdP == null)
                {
                    return View("Error");
                }
                else
                {
                    hvm.Personne = cs.ObtenirPersonne(hvm.AdP.PersonneId);
                    hvm.Adresse = cs.ObtenirAdresse(hvm.Personne.AdresseId);
                    hvm.Identifiant = cs.ObtenirIdentifiant(hvm.Personne.IdentifiantId);
                    return View(hvm);
                }
            }
            else
            {
                hvm.Adresse = cs.ObtenirAdresse(hvm.Personne.AdresseId);
                hvm.Identifiant = cs.ObtenirIdentifiant(hvm.Personne.IdentifiantId);
                hvm.AdP = adp;
                return View(hvm);
            }
        }

        public IActionResult AdPCompteInfo(AdP adp)
        {

            hvm.Personne = cs.ObtenirPersonne(adp.PersonneId);

            if (hvm.Personne == null)
            {
                return View("Error");
            }
            else
            {
                hvm.Adresse = cs.ObtenirAdresse(hvm.Personne.AdresseId);
                hvm.Identifiant = cs.ObtenirIdentifiant(hvm.Personne.IdentifiantId);
                hvm.AdP = adp;
                return View(hvm);
            }
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult CreationCompte()
        {
            
            UtilisateurViewModel viewModel = new UtilisateurViewModel() { Authentifie = SessionHelper.GetObjectFromJson<bool>(HttpContext.Session, "authentification") };
            viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);

            if (viewModel.Identifiant == null)
            {
                
                return View();
            }
            else
            {
                hvm.AdP = cs.ObtenirAdPParIdentifiant(viewModel.Identifiant.Id);
                hvm.Personne = cs.ObtenirPersonne(hvm.AdP.PersonneId);
                hvm.Adresse = cs.ObtenirAdresse(hvm.Personne.AdresseId);
                hvm.Identifiant = cs.ObtenirIdentifiant(hvm.Personne.IdentifiantId);
                return View(hvm);
            }
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult CreationCompte(Personne personne, Identifiant identifiant, Adresse adresse, AdP adp)
        {
            if (!cs.TrouverIdentifiant(identifiant))
            {
                if (personne != null && identifiant != null && adresse != null)
                {

                    int Age = personne.getAge();
                    if (Age > 18)
                    {
                        personne.EstMajeur = true;
                    }

                    if (personne.EstMajeur == true)
                    {
                        if (personne.EstEnAccord == true)
                        {
                            adp.EstAdP = true;
                            identifiant.EstAdP = adp.EstAdP;
                            adp.EstAboAnnuel = false;

                            int id = cs.AjouterIdentifiant(identifiant);

                            var userClaims = new List<Claim>()
                        {
                            new Claim(ClaimTypes.Name, id.ToString()),
                        };

                            var ClaimIdentity = new ClaimsIdentity(userClaims, "User Identity");

                            var userPrincipal = new ClaimsPrincipal(new[] { ClaimIdentity });
                            HttpContext.SignInAsync(userPrincipal);
                            bool EstUtilisateur = true;
                            SessionHelper.SetObjectAsJson(HttpContext.Session, "authentification", EstUtilisateur);

                            personne.IdentifiantId = id;

                            hvm.AdP = cs.CreerAdP(personne, adresse, adp);
                            hvm.Personne = personne;
                            hvm.Adresse = adresse;
                            hvm.Identifiant = identifiant;

                            return View(hvm);
                        }
                    }
                    hvm.Personne = personne;
                    return View(hvm);
                }
            }
            hvm.AdresseExistante = cs.TrouverIdentifiant(identifiant);
            return View(hvm);
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Paiement(HomeViewModel hvm)
        {

            UtilisateurViewModel viewModel = new UtilisateurViewModel() { Authentifie = SessionHelper.GetObjectFromJson<bool>(HttpContext.Session, "authentification") };
            viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);
            hvm.AdP = cs.ObtenirAdPParIdentifiant(viewModel.Identifiant.Id);
            if (hvm.AdP == null)
            {
                return View("Error");
            }
            else
            {
                hvm.AdP.EstAboAnnuel = true;
                hvm.AdP = cs.ModifierAdP(hvm.AdP);
                hvm.Personne = cs.ObtenirPersonne(hvm.AdP.PersonneId);
                hvm.Adresse = cs.ObtenirAdresse(hvm.Personne.AdresseId);
                hvm.Identifiant = cs.ObtenirIdentifiant(hvm.Personne.IdentifiantId);
                return RedirectToAction("Index", hvm);
            }
        }



        [HttpGet]
        public IActionResult AjouterImage(AdP adp)
        {
            hvm.AdP = adp;
            return View(hvm);
        }

        [HttpPost]
        public IActionResult AjouterImage(AdP adp, IFormFile FileToUpload)
        {
            adp.Image = FileToUpload.FileName;
            hvm.AdP = cs.ObtenirAdPParId(adp.Id);
            hvm.Personne = cs.ObtenirPersonne(hvm.AdP.PersonneId);

            cs.AjouterPhoto(FileToUpload.FileName, hvm.Personne.IdentifiantId);

            string FilePath = Path.Combine(_webHostEnvironment.WebRootPath, "ImageProfils");

            if (!Directory.Exists(FilePath))

                Directory.CreateDirectory(FilePath);

            var fileName = FileToUpload.FileName;

            var filePath = Path.Combine(FilePath, fileName);

            using (FileStream fs = System.IO.File.Create(filePath))

            {
                FileToUpload.CopyTo(fs);
            }
            return RedirectToAction("Index", hvm.AdA);
        }

        [HttpGet]
        public IActionResult ModificationCompte(AdP adp)
        {
            hvm.AdP = cs.ObtenirAdPParId(adp.Id);
            hvm.Personne = cs.ObtenirPersonne(hvm.AdP.PersonneId);
            hvm.Adresse = cs.ObtenirAdresse(hvm.Personne.AdresseId);
            hvm.Identifiant = cs.ObtenirIdentifiant(hvm.Personne.IdentifiantId);

            return View(hvm);

        }

        [HttpPost]
        public IActionResult ModificationCompte(Personne personne, Adresse adresse, AdP adp)
        {

            hvm.Adresse = cs.ModifierAdresse(adresse);
            personne.AdresseId = hvm.Adresse.Id;
            hvm.Personne = cs.ModifierPersonne(personne);
            adp.PersonneId = hvm.Personne.Id;
            hvm.AdP = cs.ModifierAdP(adp);

            UtilisateurViewModel viewModel = new UtilisateurViewModel { Authentifie = HttpContext.User.Identity.IsAuthenticated };
            if (viewModel.Authentifie)
            {
                viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);
                if (viewModel.Identifiant.EstAdP == true)
                {
                    return View("AdPCompteInfo", hvm);
                }
                else if ((viewModel.Identifiant.EstGCCQ == true) || (viewModel.Identifiant.EstGCRA == true) || (viewModel.Identifiant.EstDSI == true))
                {
                    HomeViewModel hvmAdmin = new HomeViewModel();
                    hvmAdmin.Identifiant = viewModel.Identifiant;
                    hvmAdmin.Admin = cs.ObtenirAdminParIdentifiant(viewModel.Identifiant.Id);
                    return RedirectToAction("GestionComptes", "Admin", hvmAdmin.Admin);
                }
                return View(hvm);
            }
            return Redirect("/");
        }

        public IActionResult SuppressionCompte(AdP adp)
        {
            cs.SupprimerAdP(adp.Id);
            bool EstUtilisateur = false;
            SessionHelper.SetObjectAsJson(HttpContext.Session, "authentification", EstUtilisateur);
            HttpContext.SignOutAsync();
            return Redirect("/");
        }



    }
}

Projet2/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Projet2.Helpers;
using Projet2.Models.Boutique;
using Projet2.Models.Calendriers;
using Projet2.Models.Compte;
using Projet2.Models.PanierSaisonniers;
using Projet2.Models.Mails;
using Projet2.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Projet2.Controllers
{
    public class PaymentController : Controller
    {
        // GET: /<controller>/
        public IActionResult PaiementPanier(PanierSaisonnier panierSaisonnier)
        {
            PanierSaisonnierService ctx = new PanierSaisonnierService();
            HomeViewModel hvm = new HomeViewModel();
            hvm.PanierSaisonnier = ctx.ObtientTousLesPaniers().Where(p => p.Id == panierSaisonnier.Id).FirstOrDefault();
            return View(hvm);
        }
        public IActionResult Paiement(HomeViewModel hvm)
        {
            PanierService ctx = new PanierService();
            int panierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId");
            PanierBoutique panier = ctx.ObientPanier(panierId);

            hvm.PanierBoutique = panier;
            hvm.PanierId = panierId;

            

            return View(hvm);
        }

        public IActionResult Commande()
        {
            int panierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId");
            PanierService ctx = new PanierService();
            CalendrierService csc = new CalendrierService();
            PanierBoutique panierBoutique = ctx.ObientPanier(panierId);

            HomeViewModel hvm = new HomeViewModel();
            Commande commande = new Commande() { PanierBoutiqueId = panierId };
            DateTime dateDeCommande = DateTime.Now;
            commande.DateCommande = dateDeCommande;

            while (dateDeCommande.DayOfWeek != DayOfWeek.Wednesday)
            {
                dateDeCommande = dateDeCommande.AddDays(1);
            }
            commande.DateLivraison = dateDeCommande.Date;
            

            UtilisateurViewModel viewModel = new UtilisateurViewModel { Authentifie = SessionHelper.GetObjectFromJson<bool>(HttpContext.Session, "authentification") };
            if (viewModel.Authentifie)
            {
                CompteServices cs = new CompteServices();
                viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);
                if (viewModel.Identifiant.EstAdA == true)
                {
                    commande.AdAId = cs.ObtenirAdAParIdentifiant(viewModel.Identifiant.Id).Id;

                }
                else if (viewModel.Identifiant.EstCE == true)
                {
                    commande.EntrepriseId = cs.ObtenirCCEParIdentifiant(viewModel.Identifiant.Id).Entreprise.Id;
                }

            }
            else
            {
                commande.ClientId = SessionHelper.GetObjectFromJson<Client>(HttpContext.Session, "client").Id;
            }
            
            ctx.CreerCommande(commande, panierId);
            ctx.ChangerEtatCommande(panierId, "EstEnPreparation");
            ctx.DeduireDuStock(panierBoutique);
            csc.AjouterLigneCalendrierCommande(commande);


            hvm.Commande = commande;
            hvm.PanierBoutique = panierBoutique;


            SessionHelper.SetObjectAsJson(HttpContext.Session, "panierId", 0);

            return View(hvm);
        }


        public IActionResult EtapePaiement(int Total)
        {
            PanierService ctx = new PanierService();
            int panierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId");
            PanierBoutique panierboutique = ctx.ObientPanier(panierId);
            int articleid = ctx.ArticlesPlusEnStock(panierboutique);
            if (articleid == 0)
            { 
                UtilisateurViewModel viewModel = new UtilisateurViewModel { Authentifie = SessionHelper.GetObjectFromJson<bool>(HttpContext.Session, "authentification") };
                if (viewModel.Authentifie)
                {
                    CompteServices cs = new CompteServices();
                    HomeViewModel hvm = new HomeViewModel();
                
                    viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);
                    if (viewModel.Identifiant.EstAdP == true)
                    {
                        hvm.AdP = cs.ObtenirAdPParIdentifiant(viewModel.Identifiant.Id);
                    
                        return RedirectToAction("Paiement", hvm);
                    }
                    else if (viewModel.Identifiant.EstAdA == true)
                    {
                        hvm.AdA = cs.ObtenirAdAParIdentifiant(viewModel.Identifiant.Id);
                        return RedirectToAction("Paiement", hvm);
                    }
                    else if (viewModel.Identifiant.EstCE == true)
                    {
                        hvm.ContactComiteEntreprise = cs.ObtenirCCEParIdentifiant(viewModel.Identifiant.Id);
                        return RedirectToAction("Paiement", hvm);
                    }

                }
                return RedirectToAction("FicheRenseignement");
            }
            else
            {
                return RedirectToAction("ArticleSansStock", new { articleid });
            }
        }

        public IActionResult FicheRenseignement()
        {

            return View();

        }

        [HttpPost]
        public IActionResult FicheRenseignement(Client client, Adresse adresse)
        {

            CompteServices csx = new CompteServices();
            csx.CreerClient(client, adresse);
            HomeViewModel hvm = new HomeViewModel
            {
                Client = client
            };
            SessionHelper.SetObjectAsJson(HttpContext.Session, "client", client);
            return RedirectToAction("Paiement", new { hvm });

        }

        public IActionResult ArticleSansStock(int articleid)
        {
            PanierService ctx = new PanierService();
            HomeViewModel hvm = new HomeViewModel()
            {
                Article = ctx.ObtientArticle(articleid)
            };
            return View(hvm);
        }

    }
}

Projet2/Views/Boutique/AfficherBoutique.cshtml
@model Projet2.ViewModels.HomeViewModel
@{
    ViewData["Title"] = "Boutique";
}

<div class="container-fluid afternav px-4 px-lg-5 bg-dark py-4 mb-5">
    <div class="text-center text-white">
        <h1 class="display-4 fw-bolder">Bienvenue sur notre boutique</h1>
        <p class="lead fw-normal text-white-50 mb-0">Des produits frais toute l'année</p>
    </div>
</div>

<!-- Products -->
<div class="container">
    <div class="row">
        <div class="col-md-2 menu-rigth">
            <form method="post">
                <div class="row m-2">
                    <div class="input-group">
                        <input name="recherche" type="search" class="form-control rounded" placeholder="Produit" aria-label="Produit"
                               aria-describedby="search-addon" />
                    </div>
                </div>
                <div class="row m-2">
                        <div class="form-group">
                            <select id="form_need" name="rechercheAdP" class="form-control" data-error="Producteurs">

                                <option value=""></option>

                                @foreach (Projet2.Models.Compte.AdP adp in Model.ListeComptesAdP)
                                {
                                    <option value="@adp.NomProducteur"> @adp.NomProducteur </option>
                                }
                            </select>
                        </div>
                </div>
                <div class="row m-2">


                    <button type="submit" class="btn btn-outline-primary">Recherche</button>
                </div>
            </form>
        </div>
        <div class="col-md-9">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-5">
                @foreach (Projet2.Models.Boutique.Article article in @Model.Boutiques.Articles as List<Projet2.Models.Boutique.Article>)
                {
                    @if(@article.EstValide && !@article.EstEnAttente)
                    {                                            
                    <div class="col">
                        <div class="card h-100 border-0 shadow-sm">
                            @{
                                String filepath = "~/ImageArticle/" + @article.Image;
                            }
                            <img src="~/ImageArticle/@article.Image" class="card-img-top h-30" alt="..." />
                            <div class="card-body">
                                <h5 class="card-title text-center" style="max-height: 2em">@article.Nom</h5>
                                <p class="card-text text-center" style="max-height: 4em"> @Decimal.Round(article.PrixTTC, 2) €</p>
                                <div class="d-grid gap-2 col-12 mx-auto">
                                    <button class="btn btn-outline-dark flex-shrink-0" type="button" onclick="location.href='@Url.Action("Article", "Boutique", new { @Id = article.Id })'">
                                        Voir Article
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    }
                    }                
            </div>
        </div>
    </div>
</div>

Projet2/Views/Boutique/AjouterArticle.cshtml
@model Projet2.ViewModels.HomeViewModel

@{
    ViewData["Title"] = "Ajouter Article";
}


<div class="container afternav">
    <div class="row">
        <div class="col-12 text-center"><h1>Ajouter Article</h1></div>
    </div>

    <form enctype="multipart/form-data" method="post" asp-controller="Boutique" asp-action="AjouterArticle">
    @Html.HiddenFor(m => Model.AdP.Id)
        <div class="row g-3">
            <div class="col">
                <label for="nom" class="col-sm-2 col-form-label">Nom</label>
                <input id="nom" type="text" class="form-control" name="nom">
            </div>
            <div class="col">
                <label for="description" class="col-sm-2 col-form-label">Description</label>
                <input id="description" type="text" class="form-control" name="Description">
            </div>

        </div>
        <div class="row g-3">
            <div class="col">
                <label for="prix" class="col-sm-2 col-form-label">Prix</label>
                <input id="prix" type="number" class="form-control" name="prix">
            </div>
            <div class="col">
                <label for="stock" class="col-sm-2 col-form-label">Stock</label>
                <input id="stock" type="number" class="form-control" name="Stock">
            </div>
        </div>
        <div class="row g-3">
            <div class="col">
                <label for="prixTTC" class="col-sm-2 col-form-label">PrixTTC</label>
                <input id="prixTTC" type="number" class="form-control" name="prixTTC">
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <input name="FileToUpload" type="file" value="browse" />
            </div>
            <div class="col-12">
                    <button class="btn btn-primary" type="submit" value="Submit">Ajouter</button>
            </div>
        </div>
    </form>
    <br/><br/>
     <p>@Html.ActionLink("Retour", "Index", "CompteAdP")</p>
</div>

Projet2/Views/Boutique/Article.cshtml
@model Projet2.ViewModels.HomeViewModel

@{
}

<section class="py-5 afternav">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="~/ImageArticle/@Model.Article.Image" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">Stock: @Model.Article.Stock</div>
                <h1 class="display-5 fw-bolder">@Model.Article.Nom</h1>
                <div class="fs-5 mb-5">
                    <span> @Decimal.Round(Model.Article.PrixTTC, 2) €</span>

                </div>
                <p class="lead">@Model.Article.Description</p>
                <div class="d-flex">
                    @using (Html.BeginForm())
                    {
                        @Html.HiddenFor(m => Model.Article.Id)
                        <input class="form-control text-center me-3" id="inputQuantity" type="number" min=0 value="1" style="max-width: 4rem" name="Quantite" required />
                        <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                            <i class="bi bi-basket2 me-1"></i>
                            Ajouter au panier
                        </button>
                    }
                </div>
            </div>
        </div>

            @foreach(var avis in @Model.Article.Avis)
            {
                <br/>
                @avis.Note
                <br/>
                @avis.Text
                <br/>
                @avis.AdAId
                <br/>
                <br/>
            }
    </div>
</section>

Projet2/Views/Boutique/ArticleAvis.cshtml
@model Projet2.ViewModels.HomeViewModel

@{
}

    <div class=" container">
        <div class="col-7">
            <div class="row">
                <img src="~/ImageArticle/@Model.Article.Image" />
            </div>
            <div class="row">
                @Model.Article.Nom

            </div>
        </div>
            <div class="col-5">
                @using (Html.BeginForm())
                {
                <div class="col">
                    @Html.HiddenFor(m => Model.Article.Id)
                    @Html.HiddenFor(m => Model.LignePanierBoutique.Id)
                </div>
                <div class="col">
                    @Html.LabelFor(m => Model.LignePanierBoutique.Avis.Note)
                    @Html.TextBoxFor(m => Model.LignePanierBoutique.Avis.Note)
                    
                </div>
                <div class="col">
                    @Html.LabelFor(m => Model.LignePanierBoutique.Avis.Text)
                    @Html.TextBoxFor(m => Model.LignePanierBoutique.Avis.Text)
                </div>
                <div class="col-12">
                    <button type="submit">ajouter Avis</button>
                </div>
                }
            </div>
    </div>
  

Projet2/Views/Boutique/Panier.cshtml
@model Projet2.ViewModels.HomeViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

<div class="container mt-5 p-3 rounded cart">
    <div class="row no-gutters">
        <div class="col-md-12">
            <div class="product-details mr-2">
                <h5 class="mb-3">
                    <a onclick="location.href='@Url.Action("AfficherBoutique", "Boutique")'" type="button" class="text-body">
                        <i class="fas fa-long-arrow-alt-left me-2"></i>Revenir à la boutique
                    </a>
                </h5>
                <hr>
                @{
                    int ProduitsNombres = 0;
                    foreach (Projet2.Models.Boutique.LignePanierBoutique ligne in Model.PanierBoutique.LignePanierBoutiques)
                    {
                        ProduitsNombres += ligne.Quantite;
                    }
                }

                <h6 class="mb-0">Votre Panier</h6>
                <div class="d-flex justify-content-between">
                    <span>Vous avez @ProduitsNombres articles</span>
                    <div class="d-flex flex-row align-items-center">
                        <span class="text-black-50"></span>
                        <div class="price ml-2"><span class="mr-1"></span><i class="fa fa-angle-down"></i></div>
                    </div>
                </div>

                @foreach (Projet2.Models.Boutique.LignePanierBoutique ligne in Model.PanierBoutique.LignePanierBoutiques)
                {

                    var prixTTC = Decimal.Round(ligne.Article.PrixTTC, 2);
                    var SousTotal = Decimal.Round(ligne.SousTotal, 2);

                    <form method="post" asp-controller="Boutique" asp-action="ModifierPanier">

                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div class="d-flex flex-row align-items-center">
                                        <div>
                                            <img src="~/ImageArticle/@ligne.Article.Image"
                                                 class="img-fluid rounded-3" alt="Shopping item" style="width: 65px;">
                                        </div>
                                        <div class="ms-3">
                                            <h5>@ligne.Article.Nom</h5>
                                            <p class="small mb-0" style="overflow: auto">@ligne.Article.Description</p>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center">
                                        <div style="max-width: 4rem">
                                            <input type="number" class="form-control" name="quantite" min=0 value="@ligne.Quantite" required />
                                        </div>
                                        <div style="width: 80px;">
                                            <h5 class="mb-0"> @SousTotal € </h5>
                                        </div>
                                        <div>
                                            <button class="btn btn-outline-dark flex-shrink-0" type="submit">Modifier</button>
                                            <input type="hidden" name="Id" value="@ligne.Id" />
                                        </div>
                                        <a style="color: #cecece;"><i class="bi bi-trash" type="button" onclick="location.href='@Url.Action("SupprimerLigne", "Boutique" ,new {Id= ligne.Id})'"></i></a>


                                    </div>
                                </div>
                            </div>
                        </div>


                    </form>

                }

            </div>
            <hr>

            <label for="Total">Total = @Model.PanierBoutique.Total €</label>
            <hr>

            <row class="m-2">
                <div class="text-center d-grid gap-2 col-6 mx-auto">
                    <a class="btn btn-outline-dark flex-shrink-0" type="button" asp-area="" asp-controller="Boutique" asp-action="ViderPanier">Vider le Panier</a>
                </div>
            </row>

            <form method="post" asp-controller="Payment" asp-action="EtapePaiement">
                <input type="hidden" name="Total" value="@Model.PanierBoutique.Total" />
                <row class="m-2">
                    <div class="text-center d-grid gap-2 col-6 mx-auto">
                        <button type="submit" class="btn btn-outline-dark flex-shrink-0">
                            Paiement
                        </button>
                    </div>
                </row>
            </form>
        </div>
    </div>
</div>