Projet2/Controllers/PanierController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Projet2.Helpers;
using Projet2.Models.Calendriers;
using Projet2.Models.Compte;
using Projet2.Models.PanierSaisonniers;
using Projet2.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Projet2.Controllers
{
    public class PanierController : Controller
    {
        private HomeViewModel hvm = new HomeViewModel();
        private PanierSaisonnierService ctx = new PanierSaisonnierService();
        private LignePanierService lignePanierService = new LignePanierService();
        private readonly IWebHostEnvironment _webHostEnvironment;
        private CalendrierService csv = new CalendrierService();

        public PanierController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

      
        public IActionResult AfficherPaniers()
        {
            CompteServices cs = new CompteServices();
            UtilisateurViewModel viewModel = new UtilisateurViewModel { Authentifie = SessionHelper.GetObjectFromJson<bool>(HttpContext.Session, "authentification") };
            if (viewModel.Authentifie)
            {
                viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);
                if (viewModel.Identifiant.EstAdP || viewModel.Identifiant.EstAdA || viewModel.Identifiant.EstCE || viewModel.Identifiant.EstGCRA || viewModel.Identifiant.EstGCCQ || viewModel.Identifiant.EstDSI)
                {
                    hvm.Authentifie = true; ;
                }
            }
            hvm.CataloguePanier.PanierSaisonniers = new PanierSaisonnierService().ObtientTousLesPaniers();
            return View(hvm);
        }


        public IActionResult CommanderPaniers(int id)
        {
            hvm.PanierSaisonnier = ctx.ObtientTousLesPaniers().Where(p => p.Id == id).FirstOrDefault();
            return View(hvm);
        }

        [HttpPost]
        public IActionResult CommanderPaniers( int id, int quantite, int semaine)
        {
            LignePanierService ctxligne = new LignePanierService();
            int AdAId = 0;
            int EntrepriseId = 0;

            UtilisateurViewModel viewModel = new UtilisateurViewModel { Authentifie = SessionHelper.GetObjectFromJson<bool>(HttpContext.Session, "authentification") };
            if (viewModel.Authentifie)
            {
                CompteServices cs = new CompteServices();
                viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);
                if (viewModel.Identifiant.EstAdA == true)
                {
                    AdAId = cs.ObtenirAdAParIdentifiant(viewModel.Identifiant.Id).Id;

                }
                else if (viewModel.Identifiant.EstCE == true)
                {
                    EntrepriseId = cs.ObtenirCCEParIdentifiant(viewModel.Identifiant.Id).Entreprise.Id;
                }

            }

            PanierSaisonnier panier = ctx.ObtientTousLesPaniers().Where(p => p.Id == id).FirstOrDefault();
            LignePanierSaisonnier lignePanier = ctxligne.CreerLignePanier(quantite, id, quantite * panier.Prix, semaine, AdAId, EntrepriseId);
            hvm.LignePanierSaisonnier = lignePanier;
            //return View(hvm);
            RouteValueDictionary Dict = new RouteValueDictionary();
            Dict.Add("lignePanier", lignePanier);

            return RedirectToAction("CommanderLignePanier", new { @lignepanierId = lignePanier.Id });
        }


        public IActionResult Paiement(int LignePanierId)
        {

            LignePanierSaisonnier lignePanier = lignePanierService.ObtientLignePanierParId(LignePanierId);
            CommandePanier commande = lignePanierService.CreerCommande(lignePanier);
            csv.AjouterLigneCalendrierPanier(commande);
            List<DateTime> datedeLivraison = csv.ObtenirDatesLivraisonPanierSaisonnier(commande.Id); 
            hvm.LignePanierSaisonnier = lignePanier;
            hvm.ProchaineDateLivraison = datedeLivraison[0];
            
            
            return View(hvm);
        }
      
        public IActionResult CommanderPanier(int Id)
        {

            hvm.PanierSaisonnier = ctx.ObtientTousLesPaniers().Where(p => p.Id == Id).FirstOrDefault();
            return View(hvm);
        }

        [HttpPost]
        public IActionResult CommanderPanier(int id, int quantite, int semaine)
        {
            LignePanierService ctxligne = new LignePanierService();

            int AdAId = 0;
            int EntrepriseId = 0;

            UtilisateurViewModel viewModel = new UtilisateurViewModel { Authentifie = SessionHelper.GetObjectFromJson<bool>(HttpContext.Session, "authentification") };
            if (viewModel.Authentifie)
            {
                CompteServices cs = new CompteServices();
                viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);
                if (viewModel.Identifiant.EstAdA == true)
                {
                    AdAId = cs.ObtenirAdAParIdentifiant(viewModel.Identifiant.Id).Id;

                }
                else if (viewModel.Identifiant.EstCE == true)
                {
                    EntrepriseId = cs.ObtenirCCEParIdentifiant(viewModel.Identifiant.Id).Entreprise.Id;
                }

            }

            PanierSaisonnier panier = ctx.ObtientTousLesPaniers().Where(p => p.Id == id).FirstOrDefault();
            LignePanierSaisonnier lignePanier = ctxligne.CreerLignePanier(quantite, id, quantite * panier.Prix, semaine, AdAId, EntrepriseId);
            hvm.LignePanierSaisonnier = lignePanier;
            //return View(hvm);
            RouteValueDictionary Dict = new RouteValueDictionary();
            Dict.Add("lignePanier", lignePanier);

            return RedirectToAction("CommanderLignePanier", new { @lignepanierId = lignePanier.Id });
        }

        public IActionResult CommanderLignePanier(int lignepanierId)

        {
            LignePanierSaisonnier LignePanier = lignePanierService.ObtientLignePanierParId(lignepanierId);
            hvm.PanierSaisonnier = lignePanierService.ObtientPanierParId(LignePanier.PanierSaisonnierId);
            hvm.LignePanierSaisonnier = LignePanier;
            return View(hvm);
        }

        [HttpPost]
        public IActionResult CommandeLignePanier(PanierSaisonnier panierSaisonnier, int quantite)
        {
            hvm.PanierSaisonnier = ctx.ObtientTousLesPaniers().Where(p => p.Id == panierSaisonnier.Id).FirstOrDefault();



            return View(hvm);
        }

        [HttpGet]
        public IActionResult AjouterPanier()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AjouterPanier(PanierSaisonnier panierSaisonnier, IFormFile fileToUpload)
        {

            UtilisateurViewModel viewModel = new UtilisateurViewModel { Authentifie = SessionHelper.GetObjectFromJson<bool>(HttpContext.Session, "authentification") };
            if (viewModel.Authentifie)
            {
                CompteServices cs = new CompteServices();
                viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);
                if (viewModel.Identifiant.EstAdP == true)
                {
                    AdP adp = cs.ObtenirAdPParIdentifiant(viewModel.Identifiant.Id);
                    panierSaisonnier.AdPId = adp.Id;
                    panierSaisonnier.Image = fileToUpload.FileName;
                    ctx.CreerPanierSaisonnier(panierSaisonnier);

                    // mettre le file dans le dossier
                    //var FileDic1 = "Files";

                    string FilePath1 = Path.Combine(_webHostEnvironment.WebRootPath, "Images");

                    if (!Directory.Exists(FilePath1))

                        Directory.CreateDirectory(FilePath1);

                    var fileName1 = fileToUpload.FileName;

                    var filePath1 = Path.Combine(FilePath1, fileName1);

                    using (FileStream fs = System.IO.File.Create(filePath1))

                    {
                        fileToUpload.CopyTo(fs);
                    }
                    return RedirectToAction("GestionPanier", "EspaceAdP", adp);

                }
            } return RedirectToAction("/");
          
        }

        [HttpGet]
        public IActionResult ModifierPanier(int id)
        {
            hvm.PanierSaisonnier = ctx.ObtientTousLesPaniers().Where(p => p.Id == id).FirstOrDefault();
            return View(hvm);
        }

        [HttpPost]
        public IActionResult ModifierPanier(PanierSaisonnier panierSaisonnier)
        {
            ctx.ModifierPanierSaisonnier(panierSaisonnier);
            return RedirectToAction("AfficherPaniers", panierSaisonnier.Id);
        }

        public IActionResult SupprimerPanier(PanierSaisonnier panierSaisonnier)
        {
            PanierSaisonnierService ctx = new PanierSaisonnierService();
            ctx.SupprimerPanierSaisonnier(panierSaisonnier.Id);
            return RedirectToAction("AfficherPaniers");
        }

        public bool PanierIsEmpty()
        {
            try
            {
                int PanierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId");

                return PanierId == 0;
            }
            catch (Exception)
            {
                return true;
            }
        }

        [HttpGet]
        public IActionResult PanierAvis(LignePanierSaisonnier lignePanierSaisonnier)
        {
            HomeViewModel model = new HomeViewModel();

            PanierSaisonnierService panierSaisonnierService = new PanierSaisonnierService();

Projet2/Views/EspaceAdP/ArticleModification.cshtml
@model Projet2.ViewModels.HomeViewModel

@{
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Mon Assortiment</title>
</head>
<body> 
    <div class=" container">
        <div class="col-7">
            <div class="row">
                <img src="~/ImageArticle/@Model.Article.Image" />
            </div>
            <div class="row">
            </div>
        </div>
            <div class="col-5">
                @using (Html.BeginForm())
                {
                <div class="col">
                    @Html.HiddenFor(m => Model.Article.Id)
                    @Html.HiddenFor(m => Model.Article.AdPId)
                    @Html.HiddenFor(m => Model.AdP.Id)
                </div>
                <div class="col">
                    @Html.LabelFor(m => Model.Article.Nom) :
                    @Html.TextBoxFor(m => Model.Article.Nom)
                <br/>
                    @Html.LabelFor(m => Model.Article.Description) :
                    @Html.TextBoxFor(m => Model.Article.Description)
                <br/>
                    @Html.LabelFor(m => Model.Article.Prix) :
                    @Html.TextBoxFor(m => Model.Article.Prix)
                <br/>
                    @Html.LabelFor(m => Model.Article.Stock) :
                    @Html.TextBoxFor(m => Model.Article.Stock)
                <br/>
                    @Html.LabelFor(m => Model.Article.PrixTTC) :
                    @Html.TextBoxFor(m => Model.Article.PrixTTC)
                <br/>
                @*
                    <input name="FileToUpload" type="file" value="browse" />
                    <br/>
                    @Html.LabelFor(m => Model.Upload.Name) :
                    @Html.EditorFor(m => Model.Upload.Name)
                    @Html.ValidationMessageFor(m => Model.Upload.Name, "")
                *@
                </div>
                <div class="col-12">
                <button type="submit">modifier</button>
                </div>
                }

                @Html.ActionLink("Supprimer Article", "SupprimerArticle", "EspaceAdP", @Model.Article)
            </div>
    </div>
  
</body>
</html>

Projet2/Views/EspaceAdP/CommandePanier_infos.cshtml
@model Projet2.ViewModels.HomeViewModel



<div class="container mt-5 p-3 rounded cart">
    <div class="row no-gutters">
        <div class="col-md-2 menu-rigth">
            <p>@Html.ActionLink("Retour", "CommandesAPreparer", "EspaceAdP")</p>
        </div>
        <div class="col-md-12">
            <div class="product-details mr-2">

                    <form>
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div class="d-flex flex-row align-items-center">
                                        <div>
                                            @{
                                            String filepath = "~/Images/" + @Model.CommandePanier.PanierSaisonnier.Image;
                                            }
                                            <img src="~/Images/@Model.CommandePanier.PanierSaisonnier.Image"
                                                 class="img-fluid rounded-3" alt="Shopping item" style="width: 65px;">
                                        </div>
                                        <div class="ms-3">
                                            <h5>@Model.CommandePanier.PanierSaisonnier.NomPanier</h5>
                                            <p class="small mb-0"> <br/> N° @Model.CommandePanier.ReturnNumeroCommandeForDisplay</p>
                                            <p class="small mb-0">Date de Livraison : @Model.CommandePanier.ReturnDateLivraisonForDisplayCommande</p>
                                            <p class="small mb-0">@Model.CommandePanier.PanierSaisonnier.Description</p>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center m-2">
                                        <div style="max-width: 10rem">
                                            Quantité = @Model.CommandePanier.LignePanierSaisonnier.Quantite
                                            <h5 class="mb-0">  € @Decimal.Round(Model.CommandePanier.PanierSaisonnier.Prix,2)</h5>
                                            @if (@Model.CommandePanier.EstLivre)
                                        {
                                            @if(@Model.CommandePanier.LignePanierSaisonnier.AvisId == null)
                                                    {
                                                    <p align="center">@Html.ActionLink("Donner votre avis", "ArticleAvis", "Boutique", @Model.CommandePanier.LignePanierSaisonnier)</p>
                                                    }
                                                    @if(@Model.CommandePanier.LignePanierSaisonnier.AvisId != null)
                                                    {
                                                    <p class="card-text">Avis : @Model.CommandePanier.LignePanierSaisonnier.Avis.Text</p>
                                                    <p class="card-text">Note : @Model.CommandePanier.LignePanierSaisonnier.Avis.Note </p>                                                    
                                                    }                                            
                                        }    
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
            </div>
            <hr>
            <label for="Total">Total pour @Model.CommandePanier.LignePanierSaisonnier.DureeAbonnement Semaines : @Decimal.Round(Model.CommandePanier.Total, 2) €</label>
            <hr>
        </div>
    </div>
</div>

Projet2/Views/EspaceAdP/Commande_infos.cshtml
@model Projet2.ViewModels.HomeViewModel




<div class="container mt-5 p-3 rounded cart">
    <div class="row no-gutters">
        <div class="col-md-2 menu-rigth">
            <p>@Html.ActionLink("Retour", "CommandesAPreparer", "EspaceAdP")</p>
        </div>
        <div class="col-md-12">
            <div class="product-details mr-2">

                @foreach (var lignePanierBoutique in @Model.Commande.PanierBoutique.LignePanierBoutiques)
                {

                    var prixTTC = Decimal.Round(lignePanierBoutique.Article.PrixTTC, 2);
                    var SousTotal = Decimal.Round(lignePanierBoutique.SousTotal, 2);

                    <form>

                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="d-flex justify-content-between ">
                                    <div class="d-flex flex-row align-items-center p-2">
                                        <div>
                                            <img src="~/ImageArticle/@lignePanierBoutique.Article.Image"
                                                 class="img-fluid rounded-3" alt="Shopping item" style="width: 65px;">
                                        </div>
                                        <div class="ms-3">
                                            <h5>@lignePanierBoutique.Article.AdP.NomProducteur</h5>
                                            <h5>@lignePanierBoutique.Article.Nom</h5>
                                            <p class="small mb-0">@lignePanierBoutique.Article.Description</p>
                                            <p class="small mb-0">Stock : @lignePanierBoutique.Article.Stock</p>
                                            <p class="card-text">Quantité : @lignePanierBoutique.Quantite</p>
                                            <p class="card-text">Prix : @prixTTC €</p>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-col align-items-center m-2">
                                        <div style="max-width: 10rem">
                                            Quantité = @lignePanierBoutique.Quantite
                                            <h5 class="mb-0"> <br/> € @SousTotal</h5>
                                            @if (@Model.Commande.EstLivre)
                                        {
                                            @if(@lignePanierBoutique.AvisId == null)
                                                    {
                                                    <p align="center">@Html.ActionLink("Donner votre avis", "ArticleAvis", "Boutique", @lignePanierBoutique)</p>
                                                    }
                                                    @if(@lignePanierBoutique.AvisId != null)
                                                    {
                                                    <p class="card-text">Avis : @lignePanierBoutique.Avis.Text</p>
                                                    <p class="card-text">Note : @lignePanierBoutique.Avis.Note </p>                                                    
                                                    }                                            
                                        }       
                                        </div>                                      
                                    </div>
                                </div>
                            </div>
                        </div>


                    </form>

                }

            </div>
            <hr>

            <label for="Total">Total = @Decimal.Round(Model.Commande.PanierBoutique.Total, 2) €</label>
            <hr>


        </div>
    </div>
</div>

Projet2/Views/EspaceAdP/CommandesAPreparer.cshtml
@model Projet2.ViewModels.HomeViewModel

<div class="shadow-sm p-2 mb-5 welcome">
    <h2>Mes Commandes A Préparer</h2>
</div>

<div class="container">
    
    <div class="row">
        <div class="col-md-2 menu-rigth">
            @Html.HiddenFor(m => @Model.AdP.Id)  
            <p>@Html.ActionLink("Retour", "Index", "CompteAdP", @Model.AdP)</p>  
            <p>Aujourd'hui : <script> document.write(new Date().toLocaleDateString()); </script></p>           
            <p>Prochaine Date de Livraison @Model.ReturnDateForDisplayLivraison</p>   
        </div>
        <div class="col-md-9">
            <div class="row row-cols-1 row-cols-md-4 g-5">
                
                @foreach (var commande in @Model.ListeCommandesEnPrep)
                {
                var Total = Decimal.Round(commande.PanierBoutique.Total, 2);   
                        <div class="row ">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h5 class="card-title" align="center">Boutique</h5>
                                

                                <img src="~/ImageArticle/Default.jpg" class="card-img-top" alt="..." style="width: 100%; align-content: center; height:100px"/>

                                
                                    <p class="card-text" align="center"><br/>N° @commande.ReturnNumeroCommandeForDisplay</p>
                                    <p class="card-text" align="center">@commande.ReturnDateCommandeForDisplayCommande</p>
                                    <p class="card-text" align="center">Livraison : @commande.ReturnDateForDisplayCommande</p>
                                    <p class="card-text" align="center">@commande.EtatCommande</p>
                                    <p class="card-text" align="center">@Total €</p>
                                    @if(@commande.AdA != null)
                                    {
                                    <p class="card-text"  align="center">@commande.AdA.Personne.Prenom @commande.AdA.Personne.Nom </p>
                                    }
                                    @if(@commande.Client != null)
                                    {
                                    <p class="card-text"  align="center">@commande.Client.Prenom @commande.Client.Nom </p>
                                    }
                                    @if(@commande.Entreprise != null)
                                    {
                                    <p class="card-text"  align="center">@commande.Entreprise.NomEntreprise </p>
                                    }
                                    <div align="center">
                                    <button class="btn btn-outline-dark flex-shrink-0" type="button" onclick="location.href='@Url.Action("Commande_infos", "EspaceAdP", new { @CommandeId = commande.Id })'"> voir détails</button>                                    
                                    <br/>
                                    </div>
                                    <div align="center">
                                    <form method="post" asp-controller="EspaceAdP" asp-action="CommandesAPreparer">
                                      @Html.HiddenFor(m => @Model.AdP.Id)
                                      @Html.HiddenFor(m => @commande.PanierBoutiqueId)
                                      @Html.HiddenFor(m => @commande.Id)
                                    <button id="Commande_EtatCommande" name="Commande.EtatCommande" class="btn btn-primary" type="submit" value="EstEnLivraison">Mettre en Livraison</button>                                     
                                    </form>
                                    </div>
                        </div>
            </div>                       
        </div>                    
                }

                @foreach (var commandePanier in @Model.ListeCommandesPanierEnPrep)
                {
                    var TotalPanier = Decimal.Round(commandePanier.PanierSaisonnier.Prix, 2);                   
                        <div class="row ">
                                    
                            <div class="card h-100">
                                <div class="card-body">
                                    <h5 class="card-title" align="center">Panier</h5>                                        
                                    @{
                                        String filepath = "~/ImageArticle/" + @commandePanier.PanierSaisonnier.Image;
                                    }
                                    <img src="~/Images/@commandePanier.PanierSaisonnier.Image" class="card-img-top" alt="..." style="width: 100%; align-content: center; height:100px" />                                       
                                    <p class="card-text" align="center"> <br/> N° @commandePanier.ReturnNumeroCommandeForDisplay</p>
                                    <p class="card-text" align="center">@commandePanier.ReturnDateCommandeForDisplayCommande</p>
                                    <p class="card-text" align="center">Livraison : @commandePanier.ReturnDateLivraisonForDisplayCommande</p>
                                    <p class="card-text" align="center">@commandePanier.EtatCommande</p>
                                    <p class="card-text" align="center">@TotalPanier €</p>                                    
                                    @if(@commandePanier.AdA != null)
                                    {
                                    <p class="card-text"  align="center">@commandePanier.AdA.Personne.Prenom @commandePanier.AdA.Personne.Nom </p>
                                    }
                                    
                                    @if(@commandePanier.Entreprise != null)
                                    {
                                    <p class="card-text"  align="center">@commandePanier.Entreprise.NomEntreprise </p>
                                    }
                                    <div align="center">
                                    <button class="btn btn-outline-dark flex-shrink-0" type="button" onclick="location.href='@Url.Action("CommandePanier_infos", "EspaceAdP", new { @CommandePanierId = commandePanier.Id })'"> voir détails</button>
                                    <br/>
                                    </div>
                                    <div align="center">
                                    <form method="post" asp-controller="EspaceAdP" asp-action="CommandesPanierAPreparer">
                                      @Html.HiddenFor(m => @Model.AdP.Id)
                                      @Html.HiddenFor(m => @commandePanier.Id)
                                    <button id="CommandePanier_EtatCommande" name="CommandePanier.EtatCommande" class="btn btn-primary" type="submit" value="EstEnLivraison">Mettre en Livraison</button>                                     
                                    </form>                                                                                              
                                </div>
                             </div>
                        </div>                                                                        
                    </div>                
                }
            </div>
        </div>
    </div>   
</div>

Projet2/Views/EspaceAdP/PanierModification.cshtml
@model Projet2.ViewModels.HomeViewModel
@{
    ViewData["Title"] = "ModifierPanier";
}

<div class="container mt-3">
    @using (Html.BeginForm())
    {
    <fieldset>
        <legend>Modifier un Panier : </legend>
        @Html.HiddenFor(m => Model.PanierSaisonnier.Id)
        @Html.HiddenFor(m => Model.PanierSaisonnier.Image)
        @Html.HiddenFor(m => Model.PanierSaisonnier.EstValide)
        @Html.HiddenFor(m => Model.PanierSaisonnier.EstEnAttente)
        @Html.HiddenFor(m => Model.PanierSaisonnier.AdminCommentaire)
        @Html.HiddenFor(m => Model.PanierSaisonnier.DateInscription)
        @Html.HiddenFor(m => Model.PanierSaisonnier.AdPId)
        @Html.HiddenFor(m => Model.AdP.Id)

        @Html.LabelFor(m => Model.PanierSaisonnier.NomPanier)
        @Html.TextBoxFor(m => Model.PanierSaisonnier.NomPanier)
        <br />
        @Html.LabelFor(m => Model.PanierSaisonnier.ProduitsProposes)
        @Html.TextBoxFor(m => Model.PanierSaisonnier.ProduitsProposes)
        @*@foreach (var item in Model.ProduitsProposes)
        {
        }*@
        @*<ul class=" list-group">
            @foreach (var item in Model.ProduitsProposes)
            {
                <a class="list-group-item list-group-item-action " placeholder="Small input" align-content-start asp-controller="Panier" asp-action="ModifierPanier">@item.NomProduit</a>
            }
        </ul>*@
        @Html.ValidationMessageFor(m => Model.PanierSaisonnier.ProduitsProposes)
        <br />
        @Html.LabelFor(m => Model.PanierSaisonnier.Description)
        @Html.TextAreaFor(m => Model.PanierSaisonnier.Description, new { @class = "resizer" })

        <br />
        @Html.LabelFor(m => Model.PanierSaisonnier.Prix)
        @Html.TextBoxFor(m => Model.PanierSaisonnier.Prix, "{0:n2}", new { @type = "number" })
        <br />
        <input type="submit" value="Modifier" />
    </fieldset>
    }
    <br/>
    @Html.ActionLink("Supprimer Panier", "SupprimerPanier", "EspaceAdP", @Model.PanierSaisonnier)
</div>