Projet2/Controllers/BoutiqueController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Projet2.Helpers;
using Projet2.Models.Boutique;
using Projet2.Models.Compte;
using Projet2.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Projet2.Controllers
{
    public class BoutiqueController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BoutiqueController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }


        // GET: /<controller>/
        [Authorize]
        public IActionResult AjouterArticle()
        {
            HomeViewModel hvm = new HomeViewModel
            {
                PanierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId")

            };
            return View(hvm);

        }

        [Authorize]
        [HttpPost]
        public IActionResult AjouterArticle(string nom, string description, int prix, int stock, int prixTTC, IFormFile FileToUpload)
        {
            ArticleRessources ctx = new ArticleRessources();
            UtilisateurViewModel viewModel = new UtilisateurViewModel { Authentifie = SessionHelper.GetObjectFromJson<bool>(HttpContext.Session, "authentification") };
            if (viewModel.Authentifie)
            {
                CompteServices cs = new CompteServices();   
                viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);
                if (viewModel.Identifiant.EstAdP == true)
                {
                    AdP adp = cs.ObtenirAdPParIdentifiant(viewModel.Identifiant.Id);
                    ctx.CreerArticle(nom, description, prix, stock, prixTTC, FileToUpload.FileName, adp.Id);
                
            
            
                    // mettre le file dans le dossier

                    //var FileDic = "Files";

                    string FilePath = Path.Combine(_webHostEnvironment.WebRootPath, "ImageArticle");

                    if (!Directory.Exists(FilePath))

                        Directory.CreateDirectory(FilePath);

                    var fileName = FileToUpload.FileName;

                    var filePath = Path.Combine(FilePath, fileName);

                        using (FileStream fs = System.IO.File.Create(filePath))

                        {

                            FileToUpload.CopyTo(fs);
                        }
                        return RedirectToAction("GestionBoutique", "EspaceAdP", adp);


                        }
                } return RedirectToAction("Index", "Login");            

        }


        public IActionResult AfficherBoutique()
        {
            ArticleRessources ctx = new ArticleRessources();
            CompteServices csc = new CompteServices();
            List<Article> articles = ctx.ObtientTousLesArticles();

            HomeViewModel hvm = new HomeViewModel
            {
                ListeComptesAdP = csc.ObtenirTousLesAdPs(),
                Boutiques = new Boutiques() { Articles = articles, NombreArticle = articles.Count },
                PanierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId")

            };
            return View(hvm);

        }
        [HttpPost]
        public IActionResult AfficherBoutique(String recherche, String rechercheAdP)
        {
            ArticleRessources ctx = new ArticleRessources();
            CompteServices csc = new CompteServices();
            List<Article> articles = ctx.ObtientTousLesArticles();
            List<Article>  articles2 = articles;
            List<Article> articles3 = new List<Article>();
            List<AdP> listAdP = null;

            if (recherche==null && rechercheAdP == null)
            {
                return RedirectToAction("AfficherBoutique");
            }
            else
            {
                if (rechercheAdP != null)
                {

                    listAdP = csc.ObtenirAdPParNom(rechercheAdP);
                }

                if (recherche != null)
                {
                    articles2 = articles.FindAll(x => x.Nom.ToLower().Contains(recherche.ToLower()));

                    if (listAdP != null)
                    {
                        foreach (AdP adp in listAdP)
                        {
                            List<Article> listintermediaire = articles2.FindAll(x => x.AdPId == adp.Id);

                            foreach (Article articleintermediaire in listintermediaire)
                            {
                                articles3.Add(articleintermediaire);

                            }
                        }
                    }
                    else
                    {
                        articles3 = articles2;
                    }
                }
                else if (listAdP != null)
                {
                    foreach (AdP adp in listAdP)
                    {
                        List<Article> listintermediaire = articles2.FindAll(x => x.AdPId == adp.Id);

                        foreach (Article articleintermediaire in listintermediaire)
                        {
                            articles3.Add(articleintermediaire);

                        }
                    }
                }


                HomeViewModel hvm = new HomeViewModel
                {
                    ListeComptesAdP = csc.ObtenirTousLesAdPs(),
                    Boutiques = new Boutiques() { Articles = articles3, NombreArticle = articles3.Count },
                    PanierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId")

                };
                return View(hvm);
            }
            

        }

        public IActionResult Article(int id)
        {
            ArticleRessources ctx = new ArticleRessources();
            Article article = ctx.ObtientTousLesArticles().Where(a => a.Id == id).FirstOrDefault();
            article.Avis = ctx.AfficherAvisPourArticle(article);

            HomeViewModel hvm = new HomeViewModel
            {
                Article = article,
                PanierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId")

             };
            return View(hvm);

        }

        [HttpPost]
        public IActionResult Article( int id, int Quantite)
        {
            int panierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId");

            PanierService ctx = new PanierService();
            ArticleRessources ctxarticle = new ArticleRessources();

            Article article = ctxarticle.ObtientTousLesArticles().Where(a => a.Id == id).FirstOrDefault();

            //LignePanierBoutique ligne = new LignePanierBoutique() { Article = article, Quantite = Quantite, SousTotal = article.PrixTTC * Quantite };


            if (panierId == 0) // Le panier n'existe pas dans la session
            {
                panierId = ctx.CreerPanier();
                SessionHelper.SetObjectAsJson(HttpContext.Session, "panierId", panierId);
                ctx.AjouterArticle(panierId, id, Quantite);

            }
            else // Sinon Le panier existe deja :
            {
                //PanierBoutique panier = ctx.ObientPanier(panierId);
                ctx.AjouterArticle(panierId, id, Quantite);
            }

            return RedirectToAction("Panier", new { @panierId = panierId });

        }


        public IActionResult Panier(int panierId)
        {
            PanierService ctx = new PanierService();
            PanierBoutique panier = ctx.ObientPanier(panierId);
            List < LignePanierBoutique > liste = panier.LignePanierBoutiques ;
            ctx.CalculerTotalPanier(panierId);

            HomeViewModel hvm = new HomeViewModel
            {

                PanierBoutique = panier,
                PanierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId")

            };
            return View(hvm);

            

        }
        public IActionResult IPanier()
        {
            int panierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId");

            return RedirectToAction("Panier", new { @panierId = panierId });

        }

        public IActionResult ViderPanier()
        {
            int panierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId");
            PanierService ctx = new PanierService();
            PanierBoutique panier = ctx.ObientPanier(panierId);
            ctx.ViderPanier(panier);

            return RedirectToAction("Panier", new { @panierId = panierId });

        }

        [HttpPost]
        public IActionResult ModifierPanier(int quantite, int Id)
        {
            int panierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId");
            PanierService ctx = new PanierService();
            LignePanierBoutique ligne = ctx.ObtientLigne(Id);
            Article article = ctx.ObtientArticle(ligne.ArticleId);


            ctx.ModifierLigneAbsolue(Id, quantite , article, article.PrixTTC*quantite );

            return RedirectToAction("Panier", new { @panierId = panierId });

        }
        
        public IActionResult SupprimerLigne(int Id)
        {
            int panierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId");
            PanierService ctx = new PanierService();
            LignePanierBoutique ligne = ctx.ObtientLigne(Id);


            ctx.SupprimerLignePanier(ligne);

            return RedirectToAction("Panier", new { @panierId = panierId });

        }

        [HttpGet]
        public IActionResult ArticleAvis(LignePanierBoutique lignePanierBoutique)
        {

Projet2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Projet2.Helpers;
using Projet2.Models;
using Projet2.Models.Boutique;
using Projet2.Models.Compte;
using Projet2.Models.PanierSaisonniers;
using Projet2.ViewModels;

namespace Projet2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Activite()
        {
            return View();
        }

        public IActionResult Index()
        {
            CompteServices csx = new CompteServices();
            HomeViewModel hvm = new HomeViewModel
            {
                PanierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId"),
                ListeComptesAdP = csx.ObtenirAdPsVedettes()

        };
            return View(hvm);
        }

        public IActionResult Privacy()
        {
            HomeViewModel hvm = new HomeViewModel
            {
                PanierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierId")

            };
            return View(hvm);
        }
        public IActionResult Producteurs()
        {
            HomeViewModel hvm = new HomeViewModel();
            ArticleRessources articleRessources = new ArticleRessources();
            PanierSaisonnierService saisonnierService = new PanierSaisonnierService();
            CompteServices cs = new CompteServices();

            hvm.ListeComptesAdP = cs.ObtenirTousLesAdPs();
            foreach (AdP adp in hvm.ListeComptesAdP)
            {
                if (adp.EstActive)
                {
                    foreach (Article article in articleRessources.ObtenirArticleParAdP(adp))
                    {
                        if (!article.EstValide)
                        {
                            hvm.AdP.Assortiment.Add(article);
                        }
                    }
                    foreach (PanierSaisonnier panierSaisonnier in saisonnierService.ObtenirPanierParAdP(adp))
                    {
                        if (!panierSaisonnier.EstValide)
                        {
                            hvm.AdP.AssortimentPanier.Add(panierSaisonnier);
                        }
                    }

                }
                
            }

            return View(hvm);
        }

        public IActionResult Producteur(int Id)
        {
            HomeViewModel hvm = new HomeViewModel();
            ArticleRessources articleRessources = new ArticleRessources();
            PanierSaisonnierService saisonnierService = new PanierSaisonnierService();
            CompteServices cs = new CompteServices();

            hvm.AdP = cs.ObtenirAdPParId(Id);

            //foreach (Article article in articleRessources.ObtenirArticleParAdP(hvm.AdP))
            //{
            //    if (!article.EstValide)
            //    {
            //        hvm.AdP.Assortiment.Add(article);
            //    }
            //}
            //foreach (PanierSaisonnier panierSaisonnier in saisonnierService.ObtenirPanierParAdP(hvm.AdP))
            //{
            //    if (!panierSaisonnier.EstValide)
            //    {
            //        hvm.AdP.AssortimentPanier.Add(panierSaisonnier);
            //    }
            //}
            return View(hvm);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Authorize]
        public IActionResult EspacePersonnel()
        {
            UtilisateurViewModel viewModel = new UtilisateurViewModel { Authentifie = SessionHelper.GetObjectFromJson<bool>(HttpContext.Session, "authentification") };
            if (viewModel.Authentifie)
            {
                CompteServices cs = new CompteServices();
                HomeViewModel hvm = new HomeViewModel();
                viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);
                if (viewModel.Identifiant.EstAdP == true)
                {
                    hvm.AdP = cs.ObtenirAdPParIdentifiant(viewModel.Identifiant.Id);
                    return RedirectToAction("Index", "CompteAdP", hvm.AdP);
                }
                else if (viewModel.Identifiant.EstAdA == true)
                {
                    hvm.AdA = cs.ObtenirAdAParIdentifiant(viewModel.Identifiant.Id);
                    return RedirectToAction("Index", "CompteAdA", hvm.AdA);
                }
                else if (viewModel.Identifiant.EstCE == true)
                {
                    hvm.ContactComiteEntreprise = cs.ObtenirCCEParIdentifiant(viewModel.Identifiant.Id);
                    return RedirectToAction("Index", "CompteCE", hvm.ContactComiteEntreprise);
                }
                else if ((viewModel.Identifiant.EstGCCQ == true) || (viewModel.Identifiant.EstGCRA == true) || (viewModel.Identifiant.EstDSI == true))
                {
                    hvm.Identifiant = viewModel.Identifiant;
                    hvm.Admin = cs.ObtenirAdminParIdentifiant(viewModel.Identifiant.Id);
                    return RedirectToAction("Index", "Admin", hvm.Admin);
                }
            }
            return RedirectToAction("Index", "Login");
        }

        [Authorize]
        public IActionResult CommandesUser()
        {
            UtilisateurViewModel viewModel = new UtilisateurViewModel { Authentifie = SessionHelper.GetObjectFromJson<bool>(HttpContext.Session, "authentification") };
            if (viewModel.Authentifie)
            {
                CompteServices cs = new CompteServices();
                HomeViewModel hvm = new HomeViewModel();
                viewModel.Identifiant = cs.ObtenirIdentifiant(HttpContext.User.Identity.Name);
                if (viewModel.Identifiant.EstAdP == true)
                {
                    hvm.AdP = cs.ObtenirAdPParIdentifiant(viewModel.Identifiant.Id);
                    return RedirectToAction("CommandesAPreparer", "EspaceAdP", hvm.AdP);
                }
                else if (viewModel.Identifiant.EstAdA == true)
                {
                    hvm.AdA = cs.ObtenirAdAParIdentifiant(viewModel.Identifiant.Id);
                    return RedirectToAction("Commandes", "CompteAdA", hvm.AdA);
                }
                else if (viewModel.Identifiant.EstCE == true)
                {
                    hvm.ContactComiteEntreprise = cs.ObtenirCCEParIdentifiant(viewModel.Identifiant.Id);
                    return RedirectToAction("Commandes", "CompteCE", hvm.ContactComiteEntreprise);
                }
                else if ((viewModel.Identifiant.EstGCCQ == true) || (viewModel.Identifiant.EstGCRA == true) || (viewModel.Identifiant.EstDSI == true))
                {
                    hvm.Identifiant = viewModel.Identifiant;
                    hvm.Admin = cs.ObtenirAdminParIdentifiant(viewModel.Identifiant.Id);
                    return RedirectToAction("Index", "Admin", hvm.Admin);
                }
            }
            return RedirectToAction("Index", "Login");
        }
    }
}

Projet2/Views/Home/Activite.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container-fluid d-flex align-items-center justify-content-center flex-wrap banactcustom">
    @*<i class="fas fa-tractor p-2" ></i>
    <i class="fas fa-tractor p-2" ></i>
    <i class="fas fa-tractor p-2"></i>*@
    <div class="titrecustom text-white shadow-sm"> En cours de construction, disponible prochainement... :) </div>

</div>

Projet2/Views/Home/Index.cshtml
@model Projet2.ViewModels.HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}
<!--<div class="item-active" style="background-image: url('./Images/fond.jpg'); background-position: center; background-repeat: no-repeat; background-size: cover; background-attachment: fixed;">
    -->

    <div id="carouselExampleCaptions" class="carousel slide mt-5" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner shadow-lg bg-body ">

            <div class="carousel-item active z-depth-4 flex-center" style="height: 200px">
                <img src="./Images/mer.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Des produits de la mer</h5>
                    <p>Au plus proche de la production aquacole.</p>
                </div>
            </div>
            <div class="carousel-item" style="height: 200px">
                <img src="./Images/pommes.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Des produits maraichers</h5>
                    <p>Issus de la production locale</p>
                </div>
            </div>
            <div class="carousel-item" style="height: 200px">
                <img src="./Images/onion.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5></h5>
                    <p></p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

<div class="container mt-5">

    <div class="text-center shadow-md p-4 mb-5 bg-white rounded" style="color: #F4941E">

        <h1 class="" style="font-weight: 600; font-size: 3rem; color: #F4941E;">Bienvenue sur AMAPorte</h1>
        <p class="yes">Pour un commerce biologique accessible</p>
    </div>

</div>

<div class="container-fluid">

    <section class="light">
        <div class="container py-3">
            <div class="titrecustom text-center">Nos valeurs</div>
            <section id="gallery">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4 mb-4 text-center">
                            <div class="card h-100 border-0 " style="border-radius:1rem">
                                <img src="/Images/equity.jpg" alt="" class="card-img-top">
                                <div class="card-body">
                                    <h5 class="card-title py-2" style="color: #68b430">Equité & Transparence </h5>
                                    <p class="card-text">Un partenariat équitable entre producteurs et consommateurs basé sur la confiance. La transparence dans les actes d’achat, de production, de transformation et de vente des produits agricoles</p>
                                   
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 mb-4 text-center">
                            <div class="card h-100 border-0 " style="border-radius:1rem">
                                <img src="/Images/join2.jpg" alt="" class="card-img-top">
                                <div class="card-body">
                                    <h5 class="card-title py-2" style="color: #68b430">Proximité</h5>
                                    <p class="card-text">Un commerce de proximité en vente directe, à travers la relocalisation de l’économie par un soutien à l’agriculture paysanne, la relation directe entre les producteurs et les consommateurs, circuits courts. La traçabilité des aliments et la réduction des transports</p>
                               
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 mb-4 text-center">
                            <div class="card h-100 border-0" style="border-radius:1rem">
                                <img src="/Images/conv.jpg" alt="" class="card-img-top">
                                <div class="card-body">
                                    <h5 class="card-title py-2" style="color: #68b430">Solidarité & Convivialité</h5>
                                    <p class="card-text mb-2">Solidarité économique et financière avec les producteurs, solidarité entre consommateurs.convivialité dans les échanges, au travers des liens directs entre producteurs et consommateurs, l’implication dans le fonctionnement d’AMAPorte, la participation à nos différentes activités</p>
                              
                                </div>
                            </div>
                        </div>
                       
                    
                        <div class="col-lg-4 mb-4 text-center">
                            <div class="card h-100 border-0" style="border-radius:1rem">
                                <img src="/Images/eco.jpg" alt="" class="card-img-top">
                                <div class="card-body">
                                    <h5 class="card-title py-2" style="color: #68b430">Qualité et Ecologie</h5>
                                    <p class="card-text mb-2">Une agriculture paysanne, socialement équitable et écologiquement saine : pas de pesticides ni engrais chimiques de synthèse</p>
                           
                                </div>
                            </div>
                        </div>
        

                    </div>
                </div>
            </section>
        </div>
        </section>
        </div>

<div class=" container-fluid py-3 mb-3">
    <section class="light rejoindrecustom">
        <article>
            <div>
                <img src="/Images/prod.jpg" alt="" style="border-radius: 0 1rem 1rem 0;">
            </div>
            <div class="rejoindretext">
                <div class="titrecustom">Nos producteurs</div>
                <div class=" px-3 mb-3 " style="font-style:italic">Implantés à Saint Pol de Léon, nous sommes producteurs de légumes biologiques depuis <strong>1996</strong>. 
                Toute notre histoire réside en une volonté d'un avenir meilleur dans nos assiettes et aussi pour nos papilles</div>
               
                <a class="custombtn mt-4" asp-area="" asp-controller="Home" asp-action="Producteurs">En savoir plus </a>
            </div>

        </article>
    </section>
</div>

        @*<div class=" container-fluid py-3">
            <section class="">
                <div class="container d-flex align-items-center justify-content-center flex-wrap py-3">
                    <div class="titrecustom">Nos producteurs en vedette</div>*@

                    @*@foreach (Projet2.Models.Compte.AdP adp in Model.ListeComptesAdP)
                    {
           
                        <div class=" container-fluid adpcustom">
                            <section class="rejoindrecustom">
                                <article>
                                    <div>
                                        <img src="~/ImageProfils/@adp.Image" alt="" style="border-radius: 0 1rem 1rem 0;">
                                    </div>
                                    <div class="rejoindretext">
                                        <div class="yes">@adp.NomProducteur</div>
                                        <p>@adp.Description</p>
                                        <a class="custombtn mt-4" asp-controller="" asp-action="">Découvrir</a>
                                    </div>

                                </article>
                            </section>
                        </div>
                    }*@

                @*</div>
                </section>
        </div>*@



        <div class=" container-fluid text-center mb-4">
            <section class="">
                <div class="container py-3 bg-white" style="border-radius: 1rem;">
                    <div class="titrecustom">Notre Boutique en ligne</div>

                    <p class="yes ">Des produits de qualités, finement selectionnés par nos soins pour votre plus grand plaisir</p>

                    <div class="row row-cols-1 row-cols-md-3 g-5 mt-3 px-5">
                        <div class="col">
                            <div class="card h-100 border-0">
                                <img src="/Images/conserve.jpg" class="card-img-top" alt="..." style=" position: relative; height: 250px; width: 100%; object-fit: cover;">
                                
                            </div>
                        </div>
                        <div class="col">
                            <div class="card h-100 border-0" >
                                <img src="/Images/conf.jpg" class="card-img-top" alt="..." style=" position: relative; height: 250px; width: 100%; object-fit: cover;">
                                
                            </div>
                        </div>
                        <div class="col">
                            <div class="card h-100 border-0" >
                                <img src="/Images/honey.jpg" class="card-img-top" alt="..." style=" position: relative; height: 250px; width: 100%; object-fit: cover;">
                                
                            </div>
                        </div>
                    </div>

                    <a class="custombtn my-4" asp-controller="Boutique" asp-action="AfficherBoutique">Découvrir</a>
                </div>
                    </section>
            </div>

        <div class=" container-fluid py-3 mb-3">
            <section class="light rejoindrecustom">
                <article>
                    <div>
                        <img src="/Images/join3.jpg" alt="" style="border-radius: 0 1rem 1rem 0;">
                    </div>
                    <div class="rejoindretext">
                        <div class="titrecustom">Rejoignez-nous</div>
                        <p>Vous desirez vivre cette belle aventure avec nous?</p>
                        <p class="yes">N'hesitez plus!</p>
                        <a class="custombtn mt-4" asp-controller="CompteAdA" asp-action="CreationCompte">Rejoindre</a>
                    </div>
                  
                </article>
            </section>
        </div>
          
                @*<div class="container-cardscontainer">
                    <div class="container-cardcontainer">
                        <div class="card">
                            <div class="contentleft">
                                <h2>Thierry</h2>
                                <p>La description de Thierry et sa production</p>
                                <a href="#">Lien vers la page de Thierry</a>
                            </div>
                            <img src="~/Images/Thierry.png" />
                        </div>
                    </div>
                    <div class="container-cardcontainer">
                        <div class="card">
                            <div class="contentright">
                                <h2>Thierry</h2>
                                <p>La description de Thierry et sa production</p>
                                <a href="#">Lien vers la page de Thierry</a>
                            </div>
                            <img src="~/Images/Thierry.png" />
                        </div>
                    </div>
                </div>

                <div class="container-cardscontainer">
                    <div class="container-cardcontainer">
                        <div class="card">
                            <div class="contentleft">
                                <h2>Thierry</h2>
                                <p>La description de Thierry et sa production</p>
                                <a href="#">Lien vers la page de Thierry</a>
                            </div>
                            <img src="~/Images/Thierry.png" />
                        </div>
                    </div>

                </div>*@
               

Projet2/Views/Home/Producteur.cshtml
@model Projet2.ViewModels.HomeViewModel



<div class="container afternav">
    <div class="row">
        <div class="col-12 text-center">
            <h1>Page Producteur</h1>
            <div class="justify-center">
                <table border="1">
                <tr>
                    <td>@Model.AdP.Id</td>
                    <td>@Model.AdP.NomProducteur</td>
                    <td>@Model.AdP.Description</td>
                    <td>
                        @Html.ActionLink("Retour Page Producteurs", "Producteurs", "Home")

                    </td>
                </tr>
                    

                </table>
            </div>
        </div>
    </div>
</div>